### ISSUE TITLE
Max flow changes with the value sent

### ISSUE THREAD

**Issue by JacqueGM** [chriseth/pathfinder2#31]
**Describe the bug**

To calculate the max flow we try to send a big amount e.g. 1000000000000000000000000000000000, this will return a max value of 20k, but when actually trying to send this amount the pathfinder recalculates the maxflow and it returns a lower value, making the transaction imposible with that amount and having to use an even lower value

**To Reproduce**
1. Go to 'preview.testing.circles.garden'
2. Click on 'Send'

**Expected behavior**

if the max value is 20k, when trying to send that amount we should be able to send up to that amount without this having to be recalculated (or yes but returning the real max flow)

**Comment by almereyda** [comment]
Dup of #32
